export const userStatusMockData = [
  {
    id: 1,
    userId: '1005jsc',
    password: '123@@',
    name: '조재신',
    userType: '서민',
    phone: '010-2952-1190',
    email: '1005jsc@naver.com',
    groupName: '그룹1',
    point: 100,
    gourmetType: '아재입맛',
    isMembership: false,
  },
  {
    id: 2,
    userId: 'koreachief',
    password: '123@@@',
    name: '재신조',
    userType: '평민',
    phone: '010-3636-1212',
    email: '123123@naver.com',
    groupName: '그룹2',
    point: 0,
    gourmetType: '아재입맛',
    isMembership: false,
  },
  {
    id: 3,
    userId: 'fakekoreachief',
    koko: 'koko',
    password: '1@',
    name: '재신조',
    userType: '평민',
    phone: '010-3636-1212',
    email: '123123@naver.com',
    groupName: '그룹2',
    point: 0,
    gourmetType: '아재입맛',
    isMembership: false,
  },
  {
    id: 3900990,
    userId: 'fakekoreachief',
    koko: 'koko',
    password: '1@',
    name: '재신조',
    userType: '평민',
    phone: '010-3636-1212',
    email: '123123@naver.com',
    groupName: '그룹2',
    point: 0,
    gourmetType: '아재입맛',
    isMembership: false,
  },
];

export const userStatusFields = {
  userId: '아이디',
  // password: '비밀번호',
  name: '사용자 이름',
  // userType: '유저타입 (0: 일반, 1:관리자)',
  phone: '폰 번호',
  email: '이메일',
  groupName: '그룹이름',
  point: '보유 포인트',
  // gourmetType: '미식가 타입',
  // isMembership: '멤버십 여부',
};

export const UserStatusRegisterFields = [
  // userId: '아이디',
  // groupId: '그룹아이디',
  // groupName: '그룹이름',

  {
    fieldName: 'userId',
    fieldNameKor: '사원 이름',
    placeholder: '예: 배수지',
    maxCharLength: 20,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'employeeEmail',
    fieldNameKor: '사원 이메일',
    placeholder: '예: baesuzy123@naver.com',
    maxCharLength: 30,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'employeePhone',
    fieldNameKor: '사원 전화번호',
    placeholder: '예: 010-1234-4321',
    maxCharLength: 13,
    flex: 1,
    width: undefined,
  },
];
